### ISSUE TITLE
Support multipart/form-data for large edits

### ISSUE THREAD

**Issue by mashedkeyboard** [cgt/go-mwclient#14]
Hey, thanks for the amazing library!

Currently, all edits involve using query string parameters:

https://github.com/cgt/go-mwclient/blob/8d3513b202f9de1f12d4828c6fcc3db52bbbc3c8/core.go#L184-189

[MW documentation recommends](https://www.mediawiki.org/wiki/API:Edit#Large_edits) that edits over 8000 characters in size should be sent using `multipart/form-data`, to avoid having the overhead of percent-encoding the entire contents. It'd be great to see go-mwclient support this!

**Comment by cgt** [comment]
Thanks for your interest in go-mwclient. It always make me happy to hear that someone is finding my work useful.

I am not planning on adding any new features, but I welcome contributions. However, I'm not sure how this could be implemented without adding undue complexity. Should the library automatically decide to use `multipart/form-data` for large edits? Should it always do it? Should there be a setting or a flag? How big a difference does it actually make? With the low volume of edits that my MediaWiki bots make, efficiency has never been a big concern for me.

**Comment by mashedkeyboard** [comment]
Good question. My approach to it would probably be to use URL encoding by default, but switch to `multipart/form-data` if the length of a `text` value in the `params.Values` map was greater than 8,000 bytes - not that the exact length is really what matters, so long as it's *somewhere* around there. I'd probably then have another option to let people override that somehow if they were so inclined.

I'll take a look into it over the next couple of days and drop a PR :)

**Comment by mashedkeyboard** [comment]
Hey, just taking a look at this now. Is there a reason why `Encode()` returns a `string` converted from a `bytes.Buffer` (https://github.com/cgt/go-mwclient/blob/8d3513b202f9de1f12d4828c6fcc3db52bbbc3c8/params/params.go#L108), which already implements `io.Reader`, when that `string` is promptly converted back into a `strings.Reader` (https://github.com/cgt/go-mwclient/blob/master/core.go#L205)?

**Comment by cgt** [comment]
The `params` package was directly adapted from the standard library `net/url` package. The signature of `Encode` is identical to `url.Values.Encode`. I suppose an alternative would be to return the `bytes.Buffer` instead (either as that concrete type or as an io.Reader), but that seems messy. The overhead of converting it to a `string` and then to a `strings.Reader` seems unlikely to matter, so I prefer the cleaner interface.

I see that in the years since I copied the code from the standard library, they have changed the implementation of `Encode` to use a `strings.Builder` instead of a `bytes.Buffer`, which is supposedly more efficient, but again, it seems unlikely to make much of a difference.
