### ISSUE TITLE
Cannot login on wiki.piratenpartei.de

### ISSUE THREAD

**Issue by dertuxmalwieder** [cgt/go-mwclient#16]
site, err := mwclient.New("https://wiki.piratenpartei.de/wiki/api.php", "SomeBotName")
    if err != nil {
            fmt.Printf("Fehler: %s\n", err)
            return
    }

Works.

        err = site.Login("BOTNAME", "BOTPASSWORD")
        if err != nil {
                fmt.Printf("Fehler: %s\n", err)
                return
        }

Does not work:

    Fehler: extractWarnings: key not found: {"*":"Unrecognized parameters: 'formatversion', 'type‘"}

Huh?

**Comment by cgt** [comment]
As described in the README, go-mwclient is designed to work with [formatversion=2](https://www.mediawiki.org/wiki/API:JSON_version_2) of the MediaWiki JSON API, which wiki.piratenpartei.de does not support since it is running a very old version of MediaWiki.

To get go-mwclient working on this wiki, you could try removing the `formatversion` parameter ([hereabouts](https://github.com/cgt/go-mwclient/blob/master/core.go#L160) from the requests. Advanced go-mwclient features like paginated queries would definitely break, however.

Alternatively, you could try [sadbox/mediawiki](https://github.com/sadbox/mediawiki), which I believe uses the original JSON API.
